# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TfTdYUxhcxeo82hmhmz_eCtVtR6L5FIU
"""

import numpy as np
import matplotlib.pyplot as plt

# Cargar las distancias desde el archivo generado por C++
#PARA CAMBIAR DE ARCHIVO SOLO CAMBIE EL NUMERO
#ARCHIVOS DISPONIBLES
#10, 50, 100, 500, 1000, 2000, 5000
distances = np.loadtxt('distancias/distancias_5000.txt')

# Calcular el número de bins y el ancho de las barras

min_distance = 0.00
max_distance = max(distances)
bin_width = 0.25
bin_edges = np.arange(min_distance, max_distance + bin_width, bin_width)

num_bins = len(bin_edges) - 1  # El número de bins es uno menos que el número de bordes

# Crear un histograma de barras con separación y estilo personalizado
plt.hist(distances, bins=bin_edges, alpha=0.7, color='teal', edgecolor='black', linewidth=1, label='Distancias')
plt.xlabel('Distancia Euclidiana')
plt.ylabel('Frecuencia')
plt.title('Histograma de Distancias Euclidianas (Separadas y Estilo Personalizado)')
plt.grid(axis='y', linestyle='-', alpha=0.7)
plt.grid(axis='x', linestyle='-', alpha=0.7)
plt.legend(loc='upper right')

plt.show()